[theme]
background = "#2D353B"
primary = "#D3C6AA"
secondary = "#D3C6AA"
title = "#A7C080"
playing = "#A7C080"
playing_selected = "#A7C080"
playing_bg = "#232A2E"
highlight = "#A7C080"
highlight_bg = "#232A2E"
error = "#FFE4E4"
error_bg = "#E67E80"
statusbar = "#232A2E"
statusbar_progress = "#83C092"
statusbar_bg = "#83C092"
cmdline = "#83C092"
cmdline_bg = "#3D484D"

